version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    container_name: morada-mariadb
    ports:
      - $MARIADB_LOCAL_PORT:$MARIADB_DOCKER_PORT
    environment:
      MYSQL_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MYSQL_DATABASE: $MARIADB_DATABASE
    volumes:
      - $DATA_DIRECTORY/mariadb:/var/lib/mysql
      - ../database:/docker-entrypoint-initdb.d
  back:
    container_name: morada-back
    depends_on:
      - mariadb
    build:
      context: ../../src/back/
      dockerfile: Dockerfile
    working_dir: /usr/src/morada
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - $DATA_DIRECTORY/.m2:/root/.m2
    stdin_open: true
    tty: true
  front:
    container_name: morada-front
    build:
      context: ../../src/front/
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 80:80